In [1]:
import torch

# [ empty ]
x1 = torch.empty(1)     # one scalar value
x2 = torch.empty(3)     # three scalar value
x3 = torch.empty(2,3)   # 2 dimension
x4 = torch.empty(2,2,3) # 3 dimension

# check value
print(x1)
print(x2)
print(x3)
print(x4)

tensor([0.])
tensor([0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [2]:
# [ rand ]
x1 = torch.rand(2, 2)       # 2x2 random value matrix

# [ zeros ]
x2 = torch.zeros(2, 2)      # 2x2 zero value matrix

# [ ones ]
x3 = torch.ones(2, 2)       # 2x2 one value matrix

# check value
print(x1)
print(x2)
print(x3)

tensor([[0.0653, 0.1408],
        [0.0513, 0.7154]])
tensor([[0., 0.],
        [0., 0.]])


In [4]:
# type check and set type

# [ type check ]
print(x1.dtype)

# [ set type ]
x1 = torch.ones(2, 2, dtype=torch.int)
print(x1.dtype)

# get size
print(x1.size())

torch.int32
torch.int32
torch.Size([2, 2])


In [5]:
# [ tensor ]

x1 = torch.tensor([2.5, 0.1])
print(x1)

tensor([2.5000, 0.1000])


In [9]:
# torch calculation

x1 = torch.rand(2,2)
x2 = torch.rand(2,2)
print(x1)
print(x2)

# addition
add1 = torch.add(x1, x2)
add2 = x1 + x2

print(add1)
print(add2)

x2.add_(x1)   # replace x2 value
print(x2)

# subtraction
sub1 = torch.sub(x1, x2)
sub2 = x1 - x2

print(sub1)
print(sub2)

# multiplication
mul1 = torch.mul(x1, x2)
mul2 = x1 * x2

print(mul1)
print(mul2)

# division
div1 = torch.div(x1, x2)
div2 = x1 / x2

print(div1)
print(div2)



tensor([[0.6630, 0.1679],
        [0.5999, 0.1172]])
tensor([[0.5374, 0.9454],
        [0.3481, 0.5233]])
tensor([[1.2004, 1.1133],
        [0.9480, 0.6404]])
tensor([[1.2004, 1.1133],
        [0.9480, 0.6404]])
tensor([[1.2004, 1.1133],
        [0.9480, 0.6404]])
tensor([[-0.5374, -0.9454],
        [-0.3481, -0.5233]])
tensor([[-0.5374, -0.9454],
        [-0.3481, -0.5233]])
tensor([[0.7958, 0.1869],
        [0.5686, 0.0751]])
tensor([[0.7958, 0.1869],
        [0.5686, 0.0751]])
tensor([[0.5523, 0.1508],
        [0.6328, 0.1830]])
tensor([[-0.5374, -0.9454],
        [-0.3481, -0.5233]])


In [13]:
# slice operation

x1 = torch.rand(5,3)

print(x1)
print(x1[:, 0])         # all rows & [0] col
print(x1[1, :])         # [1] row & all cols
print(x1[1, 1])         # [1] row & [1] col
print(x1[1, 1].item())  # only use it when one speific value exist => actual value

tensor([[0.7250, 0.6481, 0.5019],
        [0.3171, 0.2513, 0.4138],
        [0.5036, 0.2229, 0.3754],
        [0.9871, 0.3828, 0.8025],
        [0.7848, 0.0423, 0.6440]])
tensor([0.7250, 0.3171, 0.5036, 0.9871, 0.7848])
tensor([0.3171, 0.2513, 0.4138])
tensor(0.2513)
0.25125277042388916


In [16]:
# reshape

x1 = torch.rand(4,4)
print(x1)

y1 = x1.view(16)      # one dimension 16 value
print(y1)
print(y1.size())

y2 = x1.view(-1, 8)   # -1 들어간 값은 자동으로 x * 8 = 16해서 2로 설정됨
print(y2)
print(y2.size())

tensor([[0.7875, 0.5857, 0.2882, 0.3438],
        [0.0326, 0.1579, 0.6327, 0.4467],
        [0.7990, 0.5749, 0.4363, 0.3532],
        [0.4569, 0.3001, 0.3310, 0.8338]])
tensor([0.7875, 0.5857, 0.2882, 0.3438, 0.0326, 0.1579, 0.6327, 0.4467, 0.7990,
        0.5749, 0.4363, 0.3532, 0.4569, 0.3001, 0.3310, 0.8338])
torch.Size([16])
tensor([[0.7875, 0.5857, 0.2882, 0.3438, 0.0326, 0.1579, 0.6327, 0.4467],
        [0.7990, 0.5749, 0.4363, 0.3532, 0.4569, 0.3001, 0.3310, 0.8338]])
torch.Size([2, 8])


In [21]:
import torch
import numpy as np

# [ numpy to tensor ]
a = torch.ones(5)
print(type(a))

b = a.numpy()          # change b type tensor to numpy
print(type(b))

# a와 b는 똑같은 메모리 주소를 가르키고 있음
# a에서 값을 바꾸면 b의 값도 바뀌고
# b에서 값을 바꾸면 a의 값도 바뀜
a = a.add_(1)    # a의 값에 1씩 더하기

print(a)         # a 결과 출력 
print(b)         # b의 값은 바꾼 적이 없지만, a와 똑같은 메모리 주소를 공유하기 때문에 b의 값도 모두 2로 바뀌어 있음

# [ tensor to numpy ]
a = np.ones(5)
print(type(a))

b = torch.from_numpy(a)   # change b type numpy to tensor
print(type(b))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [22]:
# cpu and gpu

if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)     # gpu에 올라감

    y = torch.ones(5)
    y = y.to(device)                     # 마찬가지로 gpu에 올라감

    z = x + y                            # 연산은 gpu로 빠르게 연산됨

    # z.numpy() gpu에 적재되었기 때문에 오류발생 (numpy는 cpu에서만 연산가능, tensor는 cpu와 gpu에서 모두 사용가능)
    z = z.to("cpu")                      # cpu로 z 로드


In [ ]:
# requires grad

x = torch.ones(5, requires_grad=True)   # requires_grad의 기본 값은 False
print(x)