requires_grad=True와 관련된 내용

https://gaussian37.github.io/dl-pytorch-gradient/

PYTORCH 한국 사용자모임
https://tutorials.pytorch.kr/beginner/blitz/autograd_tutorial.html


In [2]:
# set requires_grad to True value

import torch

x = torch.randn(3, requires_grad=True)     # requires grad's default value is False
print(x)

y = x + 2            # grad_fn=<AddBackward0>
print(y)

z = y*y*2            # grad_fn=<MulBackward0>
print(z)

z = z.mean()         # grad_fn=<MeanBackward0>}
print(z)

z.backward()         # dz/dx
print(x.grad)

tensor([ 0.2191,  0.7855, -1.0553], requires_grad=True)
tensor([2.2191, 2.7855, 0.9447], grad_fn=<AddBackward0>)
tensor([ 9.8489, 15.5183,  1.7849], grad_fn=<MulBackward0>)
tensor(9.0507, grad_fn=<MeanBackward0>)
tensor([2.9588, 3.7140, 1.2596])


In [3]:
# set requires_grad to True value

import torch

x = torch.randn(3, requires_grad=True)     # requires grad's default value is False
print(x)

y = x + 2            # grad_fn=<AddBackward0>
print(y)

z = y*y*2            # grad_fn=<MulBackward0>
print(z)

v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)

z.backward(v)         # dz/dx
print(x.grad)

tensor([ 0.9577,  0.6118, -1.0766], requires_grad=True)
tensor([2.9577, 2.6118, 0.9234], grad_fn=<AddBackward0>)
tensor([17.4965, 13.6432,  1.7054], grad_fn=<MulBackward0>)
tensor([1.1831e+00, 1.0447e+01, 3.6937e-03])


In [6]:
# change requires gradient in the middle of code
import torch

x = torch.randn(3, requires_grad=True)     # requires grad's default value is False
print(x)

# x.requires_grad_(False) -- 1
# x.detach()              -- 2
# with torch.no_grad():   -- 3

# 1
x.requires_grad_(False)
print(x)

# 2
y = x.detach()
print(y)

# 3
with torch.no_grad():
    z = x + 2
    print(z)

tensor([ 1.9247, -1.3332,  1.3784], requires_grad=True)
tensor([ 1.9247, -1.3332,  1.3784])
tensor([ 1.9247, -1.3332,  1.3784])
tensor([3.9247, 0.6668, 3.3784])


In [9]:
# gradient value accumulated

import torch

weights = torch.ones(4, requires_grad=True)

for epoch in range(1):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)

for epoch in range(2):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)

for epoch in range(3):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])
tensor([12., 12., 12., 12.])
tensor([15., 15., 15., 15.])
tensor([18., 18., 18., 18.])


In [10]:
# gradient value accumulated
# so erase the gradient value

import torch

weights = torch.ones(4, requires_grad=True)

for epoch in range(1):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)

    weights.grad.zero_()

for epoch in range(2):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)

    weights.grad.zero_()


for epoch in range(3):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)

    weights.grad.zero_()


tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [11]:
# optimizer

import torch
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor