In [1]:
import torch
import torch.nn as nn
import numpy as np

def cross_entropy(actual, predicted):
    loss = -np.sum(actual * np.log(predicted))

    return loss

# y must be one hot encoded
# if class 0: [1, 0, 0]
# if class 1: [0, 1, 0]
# if class 2: [0, 0, 1]
Y = np.array([1,0,0])

Y_pred_good = np.array([0.7, 0.2, 0.1])     # correctly predict class 0
Y_pred_bad = np.array([0.1, 0.3, 0.6])      # badly predict class 0

loss1 = cross_entropy(Y, Y_pred_good)
loss2 = cross_entropy(Y, Y_pred_bad)

print(f"LOSS1 numpy: {loss1:.4f}")
print(f"LOSS2 numpy: {loss2:.4f}")

LOSS1 numpy: 0.3567
LOSS2 numpy: 2.3026


CAREFUL!

nn.CrossEntropyLoss applies
nn.LogSoftmax + nn.NULLoss(negative log likelihood loss)

-> No Softmax in last Layer!

Y has class labels, not One-Hot
Y_pred has raw scores (logits), no Softmax

In [8]:
# 1 sample

import torch
import torch.nn as nn
import numpy as np

loss = nn.CrossEntropyLoss()

# 1 samples
Y = torch.tensor([0])

# n_samples x n_classes = 1x3
Y_pred_good = torch.tensor([[2.0, 1.0, 0.1]])     # raw value
Y_pred_bad = torch.tensor([[0.5, 2.0, 0.3]])

loss1 = loss(Y_pred_good, Y)
loss2 = loss(Y_pred_bad, Y)

print("LOSS 1= {}".format(loss1.item()))
print("LOSS 2= {}".format(loss2.item()))

_, predictions1 = torch.max(Y_pred_good, 1)
_, predictions2 = torch.max(Y_pred_bad, 1)

print(predictions1)
print(predictions2)

LOSS 1= 0.4170299470424652
LOSS 2= 1.840616226196289
tensor([0])
tensor([1])


In [9]:
# 3 samples

import torch
import torch.nn as nn
import numpy as np

loss = nn.CrossEntropyLoss()

# 3 samples
Y = torch.tensor([2,0,1])

# n_samples x n_classes = 3x3
Y_pred_good = torch.tensor([[0.1, 1.0, 2.1], [2.0, 1.0, 0.1], [0.1, 3.0, 0.1]])     # raw value
Y_pred_bad = torch.tensor([[2.1, 1.0, 0.1], [0.1, 1.0, 2.1], [0.1, 3.0, 0.1]])

loss1 = loss(Y_pred_good, Y)
loss2 = loss(Y_pred_bad, Y)

print("LOSS 1= {}".format(loss1.item()))
print("LOSS 2= {}".format(loss2.item()))

_, predictions1 = torch.max(Y_pred_good, 1)
_, predictions2 = torch.max(Y_pred_bad, 1)

print(predictions1)
print(predictions2)

LOSS 1= 0.3018244206905365
LOSS 2= 1.6241613626480103
tensor([2, 0, 1])
tensor([0, 2, 1])


in Pytorch:
Use nn.CrossEntropyLoss()
NO SOFTMAX at the end